/** Backend API adresi (Django) */
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://ironcore-gym-dwqc.onrender.com/api';

/** Fallback: API yanıt vermezse kullanılacak sabit veriler */
export const MEMBERSHIP_PLANS = [
  {
    id: 1,
    name: "Iron Starter",
    price: 399,
    period: "Aylık",
    features: ["Tüm şubelere erişim", "Standart soyunma dolabı", "Ücretsiz Wi-Fi", "08:00 - 22:00 Erişim"],
  },
  {
    id: 2,
    name: "Gold Pro",
    price: 899,
    period: "3 Aylık",
    recommended: true,
    features: ["7/24 Erişim", "Özel antrenör (Aylık 2 seans)", "Sauna & Buhar odası", "Supplement indirimi (%10)"],
  },
  {
    id: 3,
    name: "Titanium Elite",
    price: 2999,
    period: "Yıllık",
    features: ["Sınırsız 7/24 Erişim", "Sınırsız Özel Ders", "Tüm spa imkanları", "Özel park yeri", "Misafir getirme hakkı"],
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Whey Protein Isolate",
    category: "Protein",
    price: 850,
    description: "Hızlı emilim sağlayan saf izole protein tozu. Kırmızı meyve aromalı.",
    image: "/products/whey-protein-isolate.png",
  },
  {
    id: 2,
    name: "Creatine Monohydrate",
    category: "Performans",
    price: 450,
    description: "%100 saf mikronize kreatin monohidrat. Aromasız.",
    image: "/products/creatine-monohydrate.png",
  },
  {
    id: 3,
    name: "Pre-Workout Energy",
    category: "Enerji",
    price: 550,
    description: "Antrenman öncesi patlayıcı güç ve odaklanma. Tiger's Blood aromalı.",
    image: "/products/pre-workout-energy.png",
  },
  {
    id: 4,
    name: "BCAA 4:1:1",
    category: "Amino Asit",
    price: 380,
    description: "Kas toparlanması için 4:1:1 oranında BCAA. Ananas aromalı.",
    image: "/products/bcaa-411.png",
  },
  {
    id: 5,
    name: "Multi-Vitamin Pack",
    category: "Vitamin",
    price: 220,
    description: "Sporcular için günlük all-in-one vitamin paketi. Cherry Bomb aromalı.",
    image: "/products/multi-vitamin-pack.png",
  },
  {
    id: 6,
    name: "L-Carnitine Liquid",
    category: "Yağ Yakıcı",
    price: 400,
    description: "1000 mg L-karnitin + B6. Metabolizmayı destekleyen sıvı form.",
    image: "/products/l-carnitine-liquid.png",
  },
  {
    id: 7,
    name: "Multivitamin Gummies",
    category: "Vitamin",
    price: 280,
    description: "Probiyotik destekli çoklu vitamin jelibon. Çilek aromalı, 60 adet.",
    image: "/products/multivitamin-gummies.png",
  },
];

export const EXERCISES = [
  {
    id: 1,
    name: "Bench Press",
    muscleGroup: "Göğüs",
    difficulty: "Intermediate",
    description: "Göğüs kaslarını geliştiren temel bileşik egzersiz.",
    image: "https://static.exercisedb.dev/media/EIeI8Vf.gif",
    youtubeId: "rT7DgCr-3pg",
  },
  {
    id: 2,
    name: "Squat",
    muscleGroup: "Bacak",
    difficulty: "Advanced",
    description: "Tüm alt vücudu çalıştıran kralların egzersizi.",
    image: "https://static.exercisedb.dev/media/iYzB0Cz.gif",
    youtubeId: "ultWZbUMPL8",
  },
  {
    id: 3,
    name: "Deadlift",
    muscleGroup: "Sırt",
    difficulty: "Advanced",
    description: "Posterior chain (arka zincir) için en etkili hareket.",
    image: "https://static.exercisedb.dev/media/ila4NZS.gif",
    youtubeId: "op9kVnS8Xgw",
  },
  {
    id: 4,
    name: "Bicep Curl",
    muscleGroup: "Kol",
    difficulty: "Beginner",
    description: "Pazı kaslarını izole eden temel hareket.",
    image: "https://static.exercisedb.dev/media/2NpxjC1.gif",
    youtubeId: "ykJmrZ5v0Oo",
  },
  {
    id: 5,
    name: "Shoulder Press",
    muscleGroup: "Omuz",
    difficulty: "Intermediate",
    description: "Omuz başlarını hedefleyen pres hareketi.",
    image: "https://static.exercisedb.dev/media/A6wtbuL.gif",
    youtubeId: "qEwKCR5JCog",
  },
  {
    id: 6,
    name: "Plank",
    muscleGroup: "Karın",
    difficulty: "Beginner",
    description: "Core bölgesini güçlendiren statik duruş egzersizi.",
    image: "https://static.exercisedb.dev/media/CosupLu.gif",
    youtubeId: "pSHjTRCQxIw",
  },
  {
    id: 7,
    name: "Pull Up",
    muscleGroup: "Sırt",
    difficulty: "Advanced",
    description: "Vücut ağırlığı ile sırt kanat kaslarını geliştiren hareket.",
    image: "https://static.exercisedb.dev/media/0V2YQjW.gif",
    youtubeId: "eGo4IYlbE5g",
  },
  {
    id: 8,
    name: "Tricep Dip",
    muscleGroup: "Kol",
    difficulty: "Intermediate",
    description: "Arka kol ve göğüs altını hedefleyen vücut ağırlığı hareketi.",
    image: "https://static.exercisedb.dev/media/9RT8oQW.gif",
    youtubeId: "6kALZikZKMw",
  },
  {
    id: 9,
    name: "Lateral Raise",
    muscleGroup: "Omuz",
    difficulty: "Beginner",
    description: "Omuzları genişletmek için yan omuz başı hareketi.",
    image: "https://static.exercisedb.dev/media/DsgkuIt.gif",
    youtubeId: "3VcKaXpzqRo",
  },
  {
    id: 10,
    name: "Leg Press",
    muscleGroup: "Bacak",
    difficulty: "Beginner",
    description: "Bacak kaslarını güvenli bir şekilde çalıştırmak için makine egzersizi.",
    image: "https://static.exercisedb.dev/media/10Z2DXU.gif",
    youtubeId: "IZxyjW7MPJQ",
  },
  {
    id: 11,
    name: "Crunch",
    muscleGroup: "Karın",
    difficulty: "Beginner",
    description: "Üst karın kaslarını hedefleyen temel mekik hareketi.",
    image: "https://static.exercisedb.dev/media/TFqbd8t.gif",
    youtubeId: "Xyd_fa5mEA0",
  },
  {
    id: 12,
    name: "Incline Bench Press",
    muscleGroup: "Göğüs",
    difficulty: "Intermediate",
    description: "Üst göğüs kaslarını hedefleyen eğimli sehpa presi.",
    image: "https://static.exercisedb.dev/media/3TZduzM.gif",
    youtubeId: "S_qOqQzXBQM",
  },
];
