# Generated by Django 5.2.10 on 2026-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'İletişim Mesajı', 'verbose_name_plural': 'İletişim Mesajları'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Egzersiz', 'verbose_name_plural': 'Egzersizler'},
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'verbose_name': 'Üyelik Planı', 'verbose_name_plural': 'Üyelik Planları'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş Kalemi', 'verbose_name_plural': 'Sipariş Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'Kullanıcı Üyeliği', 'verbose_name_plural': 'Kullanıcı Üyelikleri'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='Ürün resmi URL veya yol (/products/...)', max_length=500),
        ),
    ]
