# Generated by Django 5.2.10 on 2026-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube form videosu ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.CharField(blank=True, help_text='Egzersiz GIF/resim URL veya yol', max_length=500),
        ),
    ]
