# Generated by Django 5.2.10 on 2026-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0, help_text='Günlük Streak'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workouts',
            field=models.IntegerField(default=0, help_text='Antrenman Sayısı'),
        ),
    ]
